const ATTRIBUTE_LENGTH_LIMIT = 128;
const ATTRIBUTE_NUMBER_LIMIT = 256;
const TRUNCATE_REPLACEMENT = '...';
const LAUNCH_NAME_LENGTH_LIMIT = 256;
const ITEM_NAME_LENGTH_LIMIT = 1024;
const LAUNCH_DESCRIPTION_LENGTH_LIMIT = 2048;
const ITEM_DESCRIPTION_LENGTH_LIMIT = 65536;

module.exports = {
  ATTRIBUTE_LENGTH_LIMIT,
  ATTRIBUTE_NUMBER_LIMIT,
  TRUNCATE_REPLACEMENT,
  LAUNCH_NAME_LENGTH_LIMIT,
  ITEM_NAME_LENGTH_LIMIT,
  LAUNCH_DESCRIPTION_LENGTH_LIMIT,
  ITEM_DESCRIPTION_LENGTH_LIMIT,
};
